### ISSUE TITLE
The timer view is in images? Shall be text

### ISSUE THREAD

**Issue by swojtczak** [ArturGrochowski/SpeedTicTacToe#4]
Are the images the same but with different numbers? Couldn't that be the same image with rendered (written) normal text on it? Please explain.

https://github.com/ArturGrochowski/SpeedTicTacToe/blob/b94cd987459c40594cfc6338193c898678729831/app/src/main/java/com/gmail/speedtictactoe/MainActivity.java#L244

The same here:
https://github.com/ArturGrochowski/SpeedTicTacToe/blob/b94cd987459c40594cfc6338193c898678729831/app/src/main/java/com/gmail/speedtictactoe/TimerClass.java#L91

Are those images just differentiating from each other with the text?

**Comment by arturgrochowski** [comment]
I've been thinking about using the regular Button with the text writtnen on it but in that case I had a very limited options for customizing the text so I decided to use imageButton instead.

**Comment by arturgrochowski** [comment]
The "case 7" is default value (seconds) for timer when an actor  click the Timer button but doesn't choose  any of the time options.  Why is "7" and not for e.g. "0"?  Because in the worst case scenario if something gona wrong and the  duration (seconds) in the Timer would be set for "0" then during the game the player will by constantly out of time and the game could crash due to an infinite loop.
